// Code generated by MockGen. DO NOT EDIT.
// Source: loan_repository.go
//
// Generated by this command:
//
//	mockgen -source=loan_repository.go -destination=../../application/borrowbook/mocks/mock_loan_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	bookdm "github.com/YK4651/ibrary-clean-architectur/internal/domain/bookdm"
	loandm "github.com/YK4651/ibrary-clean-architectur/internal/domain/loandm"
	userdm "github.com/YK4651/ibrary-clean-architectur/internal/domain/userdm"
	gomock "go.uber.org/mock/gomock"
)

// MockLoanRepository is a mock of LoanRepository interface.
type MockLoanRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLoanRepositoryMockRecorder
	isgomock struct{}
}

// MockLoanRepositoryMockRecorder is the mock recorder for MockLoanRepository.
type MockLoanRepositoryMockRecorder struct {
	mock *MockLoanRepository
}

// NewMockLoanRepository creates a new mock instance.
func NewMockLoanRepository(ctrl *gomock.Controller) *MockLoanRepository {
	mock := &MockLoanRepository{ctrl: ctrl}
	mock.recorder = &MockLoanRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoanRepository) EXPECT() *MockLoanRepositoryMockRecorder {
	return m.recorder
}

// CountActiveLoansForBook mocks base method.
func (m *MockLoanRepository) CountActiveLoansForBook(ctx context.Context, bookID *bookdm.BookID) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveLoansForBook", ctx, bookID)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveLoansForBook indicates an expected call of CountActiveLoansForBook.
func (mr *MockLoanRepositoryMockRecorder) CountActiveLoansForBook(ctx, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveLoansForBook", reflect.TypeOf((*MockLoanRepository)(nil).CountActiveLoansForBook), ctx, bookID)
}

// CountActiveLoansForUser mocks base method.
func (m *MockLoanRepository) CountActiveLoansForUser(ctx context.Context, userID *userdm.UserID) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveLoansForUser", ctx, userID)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveLoansForUser indicates an expected call of CountActiveLoansForUser.
func (mr *MockLoanRepositoryMockRecorder) CountActiveLoansForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveLoansForUser", reflect.TypeOf((*MockLoanRepository)(nil).CountActiveLoansForUser), ctx, userID)
}

// Save mocks base method.
func (m *MockLoanRepository) Save(ctx context.Context, loan *loandm.Loan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, loan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockLoanRepositoryMockRecorder) Save(ctx, loan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockLoanRepository)(nil).Save), ctx, loan)
}
