// Code generated by MockGen. DO NOT EDIT.
// Source: borrow_book_usecase.go
//
// Generated by this command:
//
//	mockgen -source=borrow_book_usecase.go -destination=mocks/mock_repositories.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
